export enum ReconciliationJob {
  PENDING_SWEEPER = "PENDING_SWEEPER",
  LEDGER_CONSISTENCY = "LEDGER_CONSISTENCY",
  ORPHAN_DETECTOR = "ORPHAN_DETECTOR",
  IDEMPOTENCY_CLEANUP = "IDEMPOTENCY_CLEANUP",
  ACCOUNT_SANITY = "ACCOUNT_SANITY",
}
