// =========================================================
// SIMULATION TEST TYPES
// =========================================================

export type SimulationTestType =
  | "NORMAL"
  | "LOAD"
  | "SPIKE"
  | "STRESS";


// =========================================================
// SIMULATION LIFECYCLE
// =========================================================

export type SimulationStatus =
  | "QUEUED"
  | "RUNNING"
  | "COMPLETED"
  | "FAILED";


// =========================================================
// K6 STAGE
// =========================================================

export interface SimulationStage {
  duration: string;
  target: number;
}


// =========================================================
// SIMULATION CONFIGURATION
//
// NORMAL / LOAD
// ----------------
// Fixed number of VUs for a fixed duration.
//
// SPIKE / STRESS
// ----------------
// VUs are controlled through stages.
// =========================================================

export interface FixedSimulationConfig {
  testType: "NORMAL" | "LOAD";

  vus: number;

  durationSeconds: number;
}

export interface StagedSimulationConfig {
  testType: "SPIKE" | "STRESS";

  stages: SimulationStage[];

  /**
   * Total duration represented by the stages.
   *
   * This is calculated by the backend and is useful
   * for displaying the test configuration on the UI.
   */
  durationSeconds: number;
}

export type SimulationConfig =
  | FixedSimulationConfig
  | StagedSimulationConfig;


// =========================================================
// NORMALIZED SIMULATION METRICS
//
// These are the metrics the frontend should use.
//
// The frontend should NOT need to understand the
// internal k6 summary structure.
// =========================================================

export interface SimulationMetrics {
  /**
   * Total HTTP requests generated by the test.
   */
  totalRequests: number;

  /**
   * Requests per second.
   */
  throughput: number;

  /**
   * Number of HTTP requests that failed.
   */
  failedRequests: number;

  /**
   * Failed request ratio.
   *
   * Example:
   * 0.01 = 1%
   */
  failureRate: number;


  // -------------------------------------------------------
  // LATENCY
  // -------------------------------------------------------

  avgLatencyMs: number;

  p90LatencyMs: number;

  p95LatencyMs: number;

  p99LatencyMs: number;

  maxLatencyMs: number;


  // -------------------------------------------------------
  // K6 CHECKS
  // -------------------------------------------------------

  checksPassed: number;

  checksFailed: number;


  // -------------------------------------------------------
  // EXECUTION
  // -------------------------------------------------------

  /**
   * Number of completed k6 iterations.
   */
  iterations: number;

  /**
   * Maximum number of VUs actually reached.
   *
   * Particularly important for SPIKE and STRESS tests.
   */
  maxVUs: number;
}


// =========================================================
// SIMULATION STATUS FILE
//
// Stored as:
// <runId>-status.json
//
// Lifecycle:
//
// QUEUED
//   ↓
// RUNNING
//   ↓
// COMPLETED
//
// or
//
// FAILED
// =========================================================

export interface SimulationStatusFile {
  id: string;

  testType: SimulationTestType;

  status: SimulationStatus;


  // -------------------------------------------------------
  // CONFIG
  // -------------------------------------------------------

  config: SimulationConfig;


  // -------------------------------------------------------
  // PROCESS INFORMATION
  // -------------------------------------------------------

  /**
   * Number of VUs requested/reached for the simulation.
   *
   * For NORMAL / LOAD this is the configured VU count.
   *
   * For SPIKE / STRESS this represents the maximum target VUs.
   */
  requestedVUs: number;

  /**
   * Operating-system process ID of k6.
   *
   * Useful for debugging/cancellation later.
   */
  pid?: number;


  // -------------------------------------------------------
  // TIMING
  // -------------------------------------------------------

  startedAt: string;

  updatedAt: string;

  completedAt?: string;

  durationMs?: number;


  // -------------------------------------------------------
  // FAILURE
  // -------------------------------------------------------

  errorMessage?: string;
}


// =========================================================
// SIMULATION RESULT FILE
//
// Stored as:
// <runId>-result.json
//
// This file is created ONLY after a successful k6 run.
//
// The frontend primarily consumes this file.
// =========================================================

export interface SimulationResultFile {
  id: string;

  testType: SimulationTestType;

  status: "COMPLETED";


  // -------------------------------------------------------
  // TIMING
  // -------------------------------------------------------

  startedAt: string;

  completedAt: string;

  durationMs: number;


  // -------------------------------------------------------
  // CONFIGURATION
  // -------------------------------------------------------

  config: SimulationConfig;


  // -------------------------------------------------------
  // NORMALIZED METRICS
  // -------------------------------------------------------

  metrics: SimulationMetrics;


  // -------------------------------------------------------
  // RAW K6 SUMMARY
  //
  // Kept for debugging / advanced dashboard views.
  //
  // Frontend should use `metrics` for normal rendering
  // rather than parsing this object.
  // -------------------------------------------------------

  k6: unknown;
}


// =========================================================
// START RESPONSE
// =========================================================

export interface SimulationStartResponse {
  success: boolean;

  message: string;

  run: SimulationStatusFile;
}